version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app:rw
    environment:
      TZ: Asia/Tokyo
    command: ["python3", "main.py"]
    restart: unless-stopped
    tty: true