services:
  api:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./api:/usr/src/api:rw
    environment:
      TZ: Asia/Tokyo
    command: ["python3", "phonetic_api.py"]
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
